spring:
  application:
    name: spring-boiler-plate

  datasource:
    write:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
    read:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

  security:
    user:
      name: user
      password: password

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.jsb.boilerplate.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.jsb: debug
    com.jsb.boilerplate.global.config.database: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  default-consume-media-type: application/json
  default-produce-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true

jwt:
  secret: averylongsecraasssthatisatleast32bytesldddsdasd1122
  expiration_time: 86400000